name: Test

on:
  workflow_call:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-15, macos-15-intel, macos-26]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: make test
      - run: make build
      - run: make build-universal
        if: matrix.runner == 'macos-15'
